branch-defaults:
  self-hosting:
    environment: wire-selfhosting
deploy:
  artifact: aws/s3/ebs.zip
global:
  application_name: Selfhosting
  default_platform: Node.js
  default_region: eu-central-1
  sc: git
  workspace_type: Application
