branch-defaults:
  dev:
    environment: wire-webapp-dev
  master:
    environment: wire-webapp-main
deploy:
  artifact: server/dist/s3/ebs.zip
global:
  application_name: Webapp
  default_platform: Node.js
  default_region: eu-central-1
  sc: git
  workspace_type: Application
