{{- if gt (int .Values.replicaCount) 1 }}
{{- $appName := include "webapp.baseName" . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: {{ sub (int .Values.replicaCount) 1 }}
  selector:
    matchLabels:
      app: {{ $appName }}
{{- end }}
