{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webapp-http
  labels:
    app: webapp
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.http.port | default .Values.service.http.internalPort }}
      targetPort: {{ .Values.service.http.internalPort }}
  selector:
    app: webapp
{{- end }}
