name: Playwright Cells Critical Flow Tests manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - imai
          - fulu
          - staging
        default: staging

jobs:
  cells-crit-flow-tests-manual:
    uses: ./.github/workflows/run-cells-crit-flow-e2e-tests.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      WIRE_CELLS_E2E_TEST_BOT_WEBHOOK_URL: ${{ secrets.WIRE_CELLS_E2E_TEST_BOT_WEBHOOK_URL }}
