name: Run Cells Critical Flow E2E Tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  cells-crit-flow-e2e-tests:
    name: Run Playwright Cells Critical Flow Tests
    if: github.repository == 'wireapp/wire-webapp'
    runs-on: [self-hosted, Linux, X64, office]
    env:
      ENV: ${{ inputs.environment }}
      SLACK_WEBHOOK_URL: ${{ secrets.WIRE_CELLS_E2E_TEST_BOT_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.x
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps && yarn playwright install chrome

      - name: Install 1Password
        uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f

      - name: Generate env file
        run: op inject -i test/e2e_tests/.env.$ENV.tpl -o test/e2e_tests/.env
        env:
          ENV: ${{ inputs.environment }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Run critical flow tests
        run: yarn e2e-test --grep "@crit-flow-cells"

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ env.ENV }}
          path: playwright-report/

      - name: Notify on Wire if succeeded
        if: success()
        continue-on-error: true
        uses: 8398a7/action-slack@59b127a91e89ce70980e1bc926dca351ad0a1b32
        with:
          status: ${{ job.status }}
          text: |
            "✅ Cells Critical Flow E2E Tests on **${{ env.ENV }}** environment succeeded ✅"
            **CHANGELOG:** ${{ needs.changelog.outputs.changelog-url }}
            **Triggered by:** ${{ github.triggering_actor }}
            **Build log:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Notify on Wire if failed
        if: failure()
        continue-on-error: true
        uses: 8398a7/action-slack@59b127a91e89ce70980e1bc926dca351ad0a1b32
        with:
          status: ${{ job.status }}
          text: |
            "❌ Cells Critical Flow E2E Tests on **${{ env.ENV }}** environment failed ❌"
            **CHANGELOG:** ${{ needs.changelog.outputs.changelog-url }}
            **Triggered by:** ${{ github.triggering_actor }}
            **Build log:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
